[package]
name = "nesemulator"
version = "0.1.0"
authors = ["niketin <Niketin@users.noreply.github.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.2"
log = "0.4.8"
env_logger = "0.7.1"

[lib]
name = "emulator"
path = "src/lib.rs"

[[bin]]
name = "nesemulator"
path = "src/main.rs"
