[package]
name = "nesemulator"
version = "0.1.0"
authors = ["niketin <Niketin@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[lib]
name = "emulator"
path = "src/lib.rs"

[[bin]]
name = "nesemulator"
path = "src/main.rs"
