[package]
name = "nesemulator"
version = "0.2.0"
authors = ["niketin <Niketin@users.noreply.github.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.9.0"
itertools = "0.10.3"

[lib]
name = "emulator"
path = "src/lib.rs"

